name: Weekly Native Build
on:
  schedule:
    - cron: '30 8 * * 0'
jobs:
  native-check:
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, macos-latest, macos-15-intel, macos-26 ]
    uses: ./.github/workflows/native-build.yml
    with:
      platform: ${{ matrix.os }}
