name: Weekly Native Build
on:
  schedule:
    - cron: '30 8 * * 0'
jobs:
  native-check:
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, macOS-latest, macos-14 ]
    uses: ./.github/workflows/native-build.yml
    with:
      platform: ${{ matrix.os }}
